// <auto-generated />
using LigaPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LigaPro.Migrations
{
    [DbContext(typeof(LigaProContext))]
    [Migration("20250501033628_SeedEquiposYJugadoresdsad")]
    partial class SeedEquiposYJugadoresdsad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LigaPro.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosPerdidos")
                        .HasColumnType("int");

                    b.HasKey("EquipoId");

                    b.ToTable("Equipo");

                    b.HasData(
                        new
                        {
                            EquipoId = 1,
                            Descripcion = "Equipo de Guayaquil conocido como Barcelona SC.",
                            LogoUrl = "/Logos/bsc.jpeg",
                            Nombre = "BSC",
                            PartidosEmpatados = 5,
                            PartidosGanados = 3,
                            PartidosJugados = 0,
                            PartidosPerdidos = 3
                        },
                        new
                        {
                            EquipoId = 2,
                            Descripcion = "Equipo de Quito conocido como Liga Deportiva Universitaria.",
                            LogoUrl = "/Logos/ldu.png",
                            Nombre = "LDU",
                            PartidosEmpatados = 2,
                            PartidosGanados = 4,
                            PartidosJugados = 0,
                            PartidosPerdidos = 2
                        },
                        new
                        {
                            EquipoId = 3,
                            Descripcion = "Equipo de Guayaquil, conocido como Emel. Club con una historia reciente en el fútbol ecuatoriano.",
                            LogoUrl = "/Logos/emel.png",
                            Nombre = "Emel",
                            PartidosEmpatados = 3,
                            PartidosGanados = 1,
                            PartidosJugados = 0,
                            PartidosPerdidos = 4
                        },
                        new
                        {
                            EquipoId = 4,
                            Descripcion = "Equipo de Quito, conocido como Aucas, uno de los equipos históricos del fútbol ecuatoriano.",
                            LogoUrl = "/Logos/aucas.png",
                            Nombre = "Aucas",
                            PartidosEmpatados = 2,
                            PartidosGanados = 5,
                            PartidosJugados = 0,
                            PartidosPerdidos = 3
                        });
                });

            modelBuilder.Entity("LigaPro.Models.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugadorId"));

                    b.Property<int>("Asistencias")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sueldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("JugadorId");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("LigaPro.Models.Jugador", b =>
                {
                    b.HasOne("LigaPro.Models.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("LigaPro.Models.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
